---
title: "Cool Title"
author: "Chris Tastad"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
  revealjs::revealjs_presentation:
    self_contained: false
    center: false
    theme: night
    highlight: zenburn
    transition: none
    reveal_plugins: ["menu", "notes"]
    reveal_options:
      showNotes: "separate-page"
      controls: true
      height: "100%"
      margin: 0.04
      slideNumber: "c/t"
      previewLinks: true

---

## First Section Title {.center}

```{r global_options, include = F}
knitr::opts_chunk$set(eval = F, echo = F, warning = F, message = F)
```

## Body

## The End {.center}

<!-- style -->

<style>

body {
  background: #2e3440;
}

.container{
    display: flex;
}

.col{
    flex: 1;
}

div.sourceCode {
  background-color: #2e3440;
}

.sourceCode {
  background-color: #393f4b;
}

.reveal section img {
  border: 30px solid #e0e1e2;
  border-radius: 10px;
  }

.reveal p {
  text-align: left;
}

.reveal ul {
  display: block;
}

.reveal ol {
  display: block;
}

</style>

<!-- slide templates

## Section Title {.center}


## Multi-Column Slide

<div class="column">

### column1
- some cool words
- https://www.merriam-webster.com/dictionary/wherever

### column2
- some more cool words

</div>


## Figure Slide
```{r eval=T}
attach(mtcars)
par(mfrow=c(2,2))
plot(wt,mpg, main="Scatterplot of wt vs. mpg")
plot(wt,disp, main="Scatterplot of wt vs disp")
hist(wt, main="Histogram of wt")
boxplot(wt, main="Boxplot of wt")
```


## Code Slide

```{r echo = T}
x = 1
if x == 1:
    # indented four spaces
    print("x is 1.")
```

-->

